# Generated by Django 4.1.5 on 2023-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFullstack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('average_salary', models.CharField(max_length=8, verbose_name='Средняя зарплата')),
                ('profession_average_salary', models.CharField(max_length=8, verbose_name='Средняя зарплата - Fullstack-программист')),
                ('vacancy_count', models.CharField(max_length=8, verbose_name='Количество вакансий')),
                ('profession_vacancy_count', models.CharField(max_length=8, verbose_name='Количество вакансий - Fullstack-программист')),
            ],
            options={
                'verbose_name': 'Статистика по профессии',
                'verbose_name_plural': 'Статистики по профессии',
            },
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
