# Generated by Django 4.1.5 on 2023-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0002_datafullstack_delete_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('level_salary', models.CharField(max_length=8, verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Статистика по уровню зарплат',
                'verbose_name_plural': 'Статистика по уровню зарплат',
            },
        ),
    ]
