# Generated by Django 4.1.5 on 2023-01-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0003_salarylevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='Город')),
                ('part_salary', models.CharField(max_length=8, verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Статистика по доле вакансий',
                'verbose_name_plural': 'Статистика по доле вакансий',
            },
        ),
    ]
