# Generated by Django 4.1.5 on 2023-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0004_salarypart'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=15, verbose_name='Год')),
                ('list_skills', models.CharField(max_length=8, verbose_name='Топ-10 навыков')),
            ],
            options={
                'verbose_name': 'Топ-10 навыков',
                'verbose_name_plural': 'Топ-10 навыков по годам',
            },
        ),
        migrations.AlterModelOptions(
            name='datafullstack',
            options={'verbose_name': 'Статистика по профессии', 'verbose_name_plural': 'Статистик по профессии'},
        ),
        migrations.AlterModelOptions(
            name='salarylevel',
            options={'verbose_name': 'Статистика по уровню зарплат', 'verbose_name_plural': 'Статистик по уровню зарплат'},
        ),
        migrations.AlterModelOptions(
            name='salarypart',
            options={'verbose_name': 'Статистика по доле вакансий', 'verbose_name_plural': 'Статистик по доле вакансий'},
        ),
    ]
