# Generated by Django 4.1.5 on 2023-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0005_topskills_alter_datafullstack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topskills',
            name='list_skills',
            field=models.CharField(max_length=150, verbose_name='Топ-10 навыков'),
        ),
    ]
